<?php
$title = 'Users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Role</th>
            <th>&nbsp;</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->paginator as $user) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($user->getUsername()); ?></td>
                <td><?php echo $this->escapeHtml($user->getEmail()); ?></td>
                <td><?php echo $this->escapeHtml($user->getFirstName()); ?></td>
                <td><?php echo $this->escapeHtml($user->getLastName()); ?></td>
                <td>
                    <?php $roles = $user->getRole(); ?>
                    <?php foreach ($roles as $role) : ?>
                        <div><?php echo $this->escapeHtml($role->getRoleId()); ?></div>
                    <?php endforeach; ?>
                </td>
                <td>
                    <a href="<?php echo $this->url('admin', array('controller' => 'user', 'action' => 'edit', 'id' => $user->getId())); ?>">Edit</a>
                </td>
                <td>
                    <a href="<?php echo $this->url('admin', array('controller' => 'user', 'action' => 'delete', 'id' => $user->getId())); ?>" onclick="return confirm('Are you sure?')">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php
// add at the end of the file after the table
echo $this->paginationControl(
        // the paginator object
        $this->paginator, 'sliding', array('partial/paginator.phtml', 'Admin'), array(
            'route' => 'admin',
            'route_params' => array(
                'controller' => 'user',
                'action' => 'index'
            )
        )
);
?>